### PR TITLE
Add four DR400 engine gauges

### PR DESCRIPTION
**Pull request by Nicolou**
Hello,
I have added 4 instruments : 
 - a fuel pressure,
 - a battery ampere-meter
 - a tank level
 - and a generic engine gauge where you can specify which datarefs you want to monitor and others options like arc ranges, etc.

### CODE REVIEW

**Comment by dankrusi** [comment]
Great work. Do you have higher-res versions of the background plates? Furthermore, to keep everything in vector format, it would be great to get these vectorized rather than using rastered images.

**Comment by Nicolou** [comment]
thank you for your encouragements.
I don't have hi-res of background images or even in vector format.
I take them from Aircraft DR400 png images files and for the battery gauge from internet search. (I wanted exactly the Jaeger style).

**Comment by dankrusi** [comment]
I see. We'll probably need to change the graphics due to copyrights. I can work on creating vector version in October/November.

**Comment by vranki** [comment]
Yep, it shouldn't be too difficult to redraw those in vectors.

**Comment by Nicolou** [comment]
Why not, but may be it would be a little difficult to have some 3d effects. In other hand, all others ext-plane instruments are in vector style so it would be more standard to do so. 
For copyright licence, all png files from DR400 aircraft are under GPL licence. (I asked the author).

**Pull request merged**
